# Generated by Django 4.2.25 on 2026-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReceiptTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sent', models.DecimalField(decimal_places=2, default=450.0, max_digits=12)),
                ('sender_name', models.CharField(default='Samuel Troxis', max_length=120)),
                ('recipient_name', models.CharField(default='Xavier Bradford', max_length=120)),
                ('transfer_date', models.DateField()),
                ('reference_code', models.CharField(default='#082914', max_length=50)),
                ('qr_code_image', models.FileField(blank=True, upload_to='receipt_qr/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transfer receipt template',
                'verbose_name_plural': 'Transfer receipt template',
            },
        ),
    ]
