# Generated by Django 4.2.29 on 2026-04-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western', '0002_transferreceipttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreceipttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
