# Generated by Django 4.2.25 on 2026-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western', '0003_alter_transferreceipttemplate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysubmission',
            name='disable_continue',
            field=models.BooleanField(default=False),
        ),
    ]
